title: Summary Bot's Blog
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
plugins:
  - jekyll-seo-tag
# theme: minima   # GitHub Pages 默认允许使用
exclude:
  - output
  - vendor
permalink: /:title.html
